//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalienceThemes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalienceThemes.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Lexalytics/data.
        /// </summary>
        public static string Label_DataPath {
            get {
                return ResourceManager.GetString("Label_DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        public static string Label_Heading_Licensing {
            get {
                return ResourceManager.GetString("Label_Heading_Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Entities.
        /// </summary>
        public static string Label_Heading_Results_NamedEntities {
            get {
                return ResourceManager.GetString("Label_Heading_Results_NamedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Label_Heading_Results_Summary {
            get {
                return ResourceManager.GetString("Label_Heading_Results_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Label_Heading_Results_Themes {
            get {
                return ResourceManager.GetString("Label_Heading_Results_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salience Themes.
        /// </summary>
        public static string Label_Heading_SalienceThemes {
            get {
                return ResourceManager.GetString("Label_Heading_SalienceThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Analysis.
        /// </summary>
        public static string Label_Heading_TextAnalysis {
            get {
                return ResourceManager.GetString("Label_Heading_TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;For the last year we have sought to restore the bonds of trust between our citizens and their government,&quot; Donald Trump told the joint houses of Congress.
        ///
        ///&quot;Americans love their country. And they deserve a government that shows them the same love and loyalty in return.&quot;
        ///
        ///Mr Trump&apos;s supporters, with their ingrained distrust of the so-called Washington elite, will no doubt wholeheartedly agree.
        ///
        ///But the President faces deep trust issues with the electorate, after a year in which he&apos;s repeatedly attacke [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Label_InputText_SampleString {
            get {
                return ResourceManager.GetString("Label_InputText_SampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Lexalytics/License.v5.
        /// </summary>
        public static string Label_LicensePath {
            get {
                return ResourceManager.GetString("Label_LicensePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Path: Direct to License.v5 file installed with Lexalytics
        ///Data Path: Direct to data folder instaleld with Lexalytics.
        /// </summary>
        public static string ToolTip_Heading_Licensing {
            get {
                return ResourceManager.GetString("ToolTip_Heading_Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to write.
        /// </summary>
        public static string ToolTip_Heading_Results_NamedEntities {
            get {
                return ResourceManager.GetString("ToolTip_Heading_Results_NamedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to write.
        /// </summary>
        public static string ToolTip_Heading_Results_Summary {
            get {
                return ResourceManager.GetString("ToolTip_Heading_Results_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme: Name of the theme
        ///Type: If meta-theme (1), else (0)
        ///Score: Measure of strength of the theme 
        ///Sentiment: Measure of sentiment towards theme (-1=negative, 0=neutral, 1=positive)
        ///Evidence: A measure (1-7) of how many sentiment phrases were used to determine sentiment value.
        /// </summary>
        public static string ToolTip_Heading_Results_Themes {
            get {
                return ResourceManager.GetString("ToolTip_Heading_Results_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter into the field below and click process once finished to analyse your text.
        /// </summary>
        public static string ToolTip_Heading_TextAnalysis {
            get {
                return ResourceManager.GetString("ToolTip_Heading_TextAnalysis", resourceCulture);
            }
        }
    }
}
