//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalienceThemes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalienceThemes.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Lexalytics/data.
        /// </summary>
        public static string Label_DataPath {
            get {
                return ResourceManager.GetString("Label_DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        public static string Label_Heading_Licensing {
            get {
                return ResourceManager.GetString("Label_Heading_Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Label_Heading_Results {
            get {
                return ResourceManager.GetString("Label_Heading_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salience Themes.
        /// </summary>
        public static string Label_Heading_SalienceThemes {
            get {
                return ResourceManager.GetString("Label_Heading_SalienceThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Analysis.
        /// </summary>
        public static string Label_Heading_TextAnalysis {
            get {
                return ResourceManager.GetString("Label_Heading_TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia is set to welcome a brand new national payments system within the next two weeks, but the instant transfers system could bring with it an elevated risk of cyber fraud.
        ///
        ///The New Payments Platform (NPP), set to be unveiled in early-to-mid February, will do away with the days of waiting up to three days for a bank transaction to be finalised, but also puts more pressure on login and password security, an industry expert has warned.
        ///
        ///The system will allow Australians to create a “payment ID” using [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Label_InputText_SampleString {
            get {
                return ResourceManager.GetString("Label_InputText_SampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Lexalytics/License.v5.
        /// </summary>
        public static string Label_LicensePath {
            get {
                return ResourceManager.GetString("Label_LicensePath", resourceCulture);
            }
        }
    }
}
